In [2]:
import pandas as pd

students = pd.DataFrame(
    {
        "Student_id" : [101,102,103,104],
        "Name" : ["Joy","Rohan","Toy","Roy"],
        "Age" : [20,21,19,22]
    }
)

Scores = pd.DataFrame({
    "Student_id" : [101,102,103,105],
    "Subject" : ["Maths", "Science","Hindi","English"],
    "Scores" : [90,98,89,78]

})

print(students)
print(Scores)

   Student_id   Name  Age
0         101    Joy   20
1         102  Rohan   21
2         103    Toy   19
3         104    Roy   22
   Student_id  Subject  Scores
0         101    Maths      90
1         102  Science      98
2         103    Hindi      89
3         105  English      78

In [ ]:
# Inner Join

inner_join = pd.merge(students,Scores,on='Student_id')

inner_join

   Student_id   Name  Age  Subject  Scores
0         101    Joy   20    Maths      90
1         102  Rohan   21  Science      98
2         103    Toy   19    Hindi      89

In [5]:
# Left Join

Left_join = pd.merge(students,Scores,on='Student_id', how="left")

Left_join

   Student_id   Name  Age  Subject  Scores
0         101    Joy   20    Maths    90.0
1         102  Rohan   21  Science    98.0
2         103    Toy   19    Hindi    89.0
3         104    Roy   22      NaN     NaN

In [7]:
#Right Join

Right_join = pd.merge(students,Scores,on='Student_id', how="right")

Right_join

   Student_id   Name   Age  Subject  Scores
0         101    Joy  20.0    Maths      90
1         102  Rohan  21.0  Science      98
2         103    Toy  19.0    Hindi      89
3         105    NaN   NaN  English      78

In [8]:
# Outer Join

Outer_join = pd.merge(students,Scores,on='Student_id', how="outer")

Outer_join

   Student_id   Name   Age  Subject  Scores
0         101    Joy  20.0    Maths    90.0
1         102  Rohan  21.0  Science    98.0
2         103    Toy  19.0    Hindi    89.0
3         104    Roy  22.0      NaN     NaN
4         105    NaN   NaN  English    78.0